version: "3.3"
services:
  postgres:
    image: "postgres:11.9"
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    expose:
      - 5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  api:
    build: 
      context: api
    ports:
      - "5001:80"
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGHOST: postgres
      PGPORT: 5432
      DJANGO_SETTINGS_MODULE: valsroom.settings_prod
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    volumes:
      - .:/usr/src/app
    command: gunicorn valsroom.wsgi --bind=0.0.0.0 --workers=1 
    depends_on:
      - postgres