version: "3.3"
services:
  postgres:
    image: "postgres:11.9"
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PORT: ${PGPORT}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    network_mode: host

  api:
    build: 
      context: api
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      VALSROOM_PORT: ${VALSROOM_PORT}
      DJANGO_SETTINGS_MODULE: valsroom.settings_prod
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    volumes:
      - ./api:/usr/src/app
      - ./log:/var/log/app
    command: gunicorn valsroom.wsgi -c valsroom/gunicorn.conf.py
    depends_on:
      - postgres
    network_mode: host