version: "3.3"
services:
  postgres:
    image: "postgres:11.9"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: valsroom
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  site:
    user: "${UID}:${GID}"
    build:
      context: site
    command: npm run serve
    volumes:
      - ./site:/usr/src/app

  api:
    build: 
      context: api
    ports:
      - "5000:5000"
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGHOST: postgres
      PGPORT: 5432
      DJANGO_SETTINGS_MODULE: valsroom.settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    volumes:
      - ./api:/usr/src/app
    command: python manage.py runserver 0.0.0.0:5000
    depends_on:
      - postgres
      - site