# Generated by Django 3.2.5 on 2021-07-30 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('japanese_name', models.TextField()),
                ('stars', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('content', models.IntegerField()),
                ('price', models.IntegerField()),
                ('abv', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('drink_name', models.CharField(max_length=255)),
                ('base_price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.drink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.valsroomuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrinkIngredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ingredient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='drink',
            name='ingredients',
            field=models.ManyToManyField(to='api.DrinkIngredient'),
        ),
        migrations.AddField(
            model_name='drink',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
    ]
