version: "3.3"
services:
  postgres:
    image: "postgres:11.9"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: valsroom
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  api:
    user: "1000:1000"
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - .:/usr/src/app
    command: python manage.py runserver 0.0.0.0:5000
    depends_on:
      - postgres