version: "3.3"
services:
  postgres:
    image: "postgres:11.9"
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    expose:
      - ${PGPORT}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "${VALSROOM_PORT}:5000"
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGHOST: postgres
    volumes:
      - .:/usr/src/app
    command: python manage.py runserver 0.0.0.0:5000
    depends_on:
      - postgres